# Generated by Django 4.2.4 on 2024-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
