# Generated by Django 4.2.4 on 2024-04-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_imageb_product_imagec'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_id',
            field=models.FloatField(default=False),
        ),
    ]
