# Generated by Django 4.2.4 on 2024-04-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_id',
        ),
    ]
